#!/usr/bin/env bash
# =============================================================================
# BirdWatch HTTPS Setup Script
# =============================================================================
# Installs nginx as a TLS reverse proxy in front of BirdWatch (port 8080).
# Generates a self-signed certificate valid for the server's local IP address.
# Redirects HTTP (port 80) to HTTPS (port 443) automatically.
#
# Usage (run as root or with sudo):
#   sudo bash scripts/setup_https.sh
#
# After running, open:
#   https://<server-ip>/
#
# Your browser will warn about the self-signed certificate.
# See the "Trusting the certificate" section at the end of this script's output.
# =============================================================================

set -e

BIRDWATCH_DIR="/opt/birdwatch"
BIRDWATCH_PORT=8080
CERT_DIR="/etc/ssl/birdwatch"
NGINX_CONF="/etc/nginx/sites-available/birdwatch"
NGINX_ENABLED="/etc/nginx/sites-enabled/birdwatch"
CONFIG_YAML="${BIRDWATCH_DIR}/config/config.yaml"

# ── Colour helpers ────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
section() { echo -e "\n${GREEN}=== $* ===${NC}"; }

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo -e "${RED}[ERROR]${NC} This script must be run as root: sudo bash scripts/setup_https.sh"
    exit 1
fi

# ── Detect server IP ──────────────────────────────────────────────────────────
SERVER_IP=$(hostname -I | awk '{print $1}')
if [ -z "$SERVER_IP" ]; then
    echo -e "${RED}[ERROR]${NC} Could not detect server IP address."
    exit 1
fi
info "Detected server IP: ${SERVER_IP}"

# ── 1. Install dependencies ───────────────────────────────────────────────────
section "Installing dependencies"

apt-get update -qq

if ! command -v nginx &>/dev/null; then
    info "Installing nginx..."
    apt-get install -y -qq nginx
    info "nginx installed"
else
    info "nginx already installed"
fi

if ! command -v openssl &>/dev/null; then
    info "Installing openssl..."
    apt-get install -y -qq openssl
fi

# ── 2. Generate self-signed certificate ──────────────────────────────────────
section "Generating self-signed TLS certificate"

mkdir -p "$CERT_DIR"

openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
    -keyout "${CERT_DIR}/birdwatch.key" \
    -out    "${CERT_DIR}/birdwatch.crt" \
    -subj   "/C=US/ST=Local/L=Local/O=BirdWatch/OU=BirdWatch/CN=${SERVER_IP}" \
    -addext "subjectAltName=IP:${SERVER_IP},IP:127.0.0.1" \
    2>/dev/null

chmod 600 "${CERT_DIR}/birdwatch.key"
chmod 644 "${CERT_DIR}/birdwatch.crt"

info "Certificate: ${CERT_DIR}/birdwatch.crt  (valid 10 years)"
info "Private key: ${CERT_DIR}/birdwatch.key"

# Copy cert to BirdWatch static folder so it can be downloaded from the browser
if [ -d "${BIRDWATCH_DIR}/birdwatch/static" ]; then
    cp "${CERT_DIR}/birdwatch.crt" "${BIRDWATCH_DIR}/birdwatch/static/birdwatch-ca.crt"
    chown birdwatch:birdwatch "${BIRDWATCH_DIR}/birdwatch/static/birdwatch-ca.crt" 2>/dev/null || true
    info "Certificate also available at https://${SERVER_IP}/birdwatch-ca.crt for easy download"
fi

# ── 3. Write nginx configuration ─────────────────────────────────────────────
section "Writing nginx configuration"

cat > "$NGINX_CONF" << NGINXEOF
# BirdWatch HTTPS reverse proxy
# Generated by scripts/setup_https.sh

# HTTPS server
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate     ${CERT_DIR}/birdwatch.crt;
    ssl_certificate_key ${CERT_DIR}/birdwatch.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    # Proxy all requests to BirdWatch FastAPI (including WebSocket)
    location / {
        proxy_pass          http://127.0.0.1:${BIRDWATCH_PORT};
        proxy_http_version  1.1;

        # WebSocket upgrade headers
        proxy_set_header    Upgrade     \$http_upgrade;
        proxy_set_header    Connection  "upgrade";

        # Standard proxy headers
        proxy_set_header    Host              \$host;
        proxy_set_header    X-Real-IP         \$remote_addr;
        proxy_set_header    X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto \$scheme;

        # Long timeouts to keep WebSocket connections alive
        proxy_read_timeout  86400;
        proxy_send_timeout  86400;
        proxy_connect_timeout 30;
    }
}

# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name _;
    return 301 https://\$host\$request_uri;
}
NGINXEOF

info "nginx config written to ${NGINX_CONF}"

# Enable site, remove default
ln -sf "$NGINX_CONF" "$NGINX_ENABLED"
rm -f /etc/nginx/sites-enabled/default

# Test config before applying
info "Testing nginx configuration..."
nginx -t

# ── 4. Update BirdWatch to listen on localhost only ───────────────────────────
section "Updating BirdWatch configuration"

if [ -f "$CONFIG_YAML" ]; then
    # Change server.host from 0.0.0.0 to 127.0.0.1 so only nginx can reach it
    if grep -q "host: 0.0.0.0" "$CONFIG_YAML"; then
        sed -i 's/host: 0\.0\.0\.0/host: 127.0.0.1/' "$CONFIG_YAML"
        info "server.host changed to 127.0.0.1 (nginx handles external connections)"
    elif grep -q "host: 127.0.0.1" "$CONFIG_YAML"; then
        info "server.host already set to 127.0.0.1"
    else
        warn "Could not update server.host in ${CONFIG_YAML} — check manually"
    fi
else
    warn "config.yaml not found at ${CONFIG_YAML} — skipping host update"
fi

# ── 5. Enable and start services ─────────────────────────────────────────────
section "Starting services"

systemctl enable nginx
systemctl restart nginx
info "nginx started"

if systemctl is-active --quiet birdwatch; then
    systemctl restart birdwatch
    info "BirdWatch restarted"
else
    warn "BirdWatch service not running — start it with: sudo systemctl start birdwatch"
fi

# ── 6. Open firewall ports ────────────────────────────────────────────────────
section "Firewall"

if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
    ufw allow 80/tcp  comment "BirdWatch HTTP redirect" 2>/dev/null || true
    ufw allow 443/tcp comment "BirdWatch HTTPS"         2>/dev/null || true
    info "ufw rules added for ports 80 and 443"
else
    warn "ufw not active — ensure ports 80 and 443 are open in your firewall"
fi

# ── 7. Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}============================================================${NC}"
echo -e "${GREEN}  HTTPS setup complete!${NC}"
echo -e "${GREEN}============================================================${NC}"
echo ""
echo -e "  Dashboard: ${GREEN}https://${SERVER_IP}/${NC}"
echo ""
echo -e "${YELLOW}  Browser security warning${NC}"
echo "  Your browser will show a warning because the certificate is"
echo "  self-signed. Accept it once using:"
echo "    Chrome / Edge : Advanced -> Proceed to ${SERVER_IP}"
echo "    Firefox       : Advanced -> Accept the Risk"
echo "    Safari        : Show Details -> visit this website"
echo ""
echo -e "${YELLOW}  Permanently trust the certificate (recommended)${NC}"
echo "  Download the certificate from:"
echo "    https://${SERVER_IP}/birdwatch-ca.crt"
echo ""
echo "  Then install it as a trusted root on your LAN devices:"
echo ""
echo "  Windows (run PowerShell as Administrator):"
echo "    Import-Certificate -FilePath birdwatch-ca.crt \\"
echo "      -CertStoreLocation Cert:\\LocalMachine\\Root"
echo ""
echo "  macOS:"
echo "    sudo security add-trusted-cert -d -r trustRoot \\"
echo "      -k /Library/Keychains/System.keychain birdwatch-ca.crt"
echo ""
echo "  Android:"
echo "    Settings -> Security -> Install from storage -> birdwatch-ca.crt"
echo ""
echo "  Linux (Ubuntu/Debian):"
echo "    sudo cp birdwatch-ca.crt /usr/local/share/ca-certificates/"
echo "    sudo update-ca-certificates"
echo ""
echo "  Alternatively, copy the cert from the server:"
echo "    scp birdwatch@${SERVER_IP}:${CERT_DIR}/birdwatch.crt ."
echo -e "${GREEN}============================================================${NC}"
